export const jabraTutorTestPassword = "JabraTutor@gmail.com";
export const jabraStudentTestPassword = "JabraStudent@gmail.com";
export const testToken = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7InBhc3N3b3JkIjoiSmFicmFUdXRvckBnbWFpbC5jb20ifSwiaWF0IjoxNjA3NTkyMDU0fQ.mhO7Ihj9t8nyRWnJxq08DDN9DuDlKuQbYLY9Iz1tRAg";